# Generated by Django 2.2.5 on 2019-09-12 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mLab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlab',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
