# Generated by Django 2.2.3 on 2019-08-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('mLab_name', models.CharField(max_length=255)),
                ('mLab_city_location', models.CharField(max_length=255)),
                ('mLab_department', models.CharField(max_length=255)),
                ('clinical_condition', models.CharField(max_length=255)),
            ],
        ),
    ]
