# Generated by Django 2.2.3 on 2019-08-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlab',
            name='session_drs',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlab',
            name='session_videos',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
    ]
