# Generated by Django 2.2.4 on 2019-08-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20190831_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlab',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='mlab',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
